trigger:
  - master

pool:
  vmImage: 'ubuntu-16.04'

steps:
  - task: CopyFiles@2
    inputs:
      Contents: 'kube-config-*.yml'
      TargetFolder: '$(build.artifactstagingdirectory)'
    displayName: 'Copy Kube Config'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'manifest'
      publishLocation: 'Container'
    displayName: 'Publish Kube Config Files'
