version: '2'

services:
  webprotege:
    image: skyplabs/webprotege
    depends_on:
      - mongodb
    ports:
      - "8888:8080"
    volumes:
      - webprotege_data:/data/webprotege

  mongodb:
    image: mongo:3
    volumes:
      - mongodb_data:/data/db

volumes:
  webprotege_data:

  mongodb_data:
