version: '2'

services:
  webprotege:
    image: dataservices.azurecr.io/ita-webprotege/web
    depends_on:
      - mongodb
    ports:
      - "8888:8080"
    volumes:
      - webprotege_data:/data/webprotege

  mongodb:
    image: dataservices.azurecr.io/ita-webprotege/db
    volumes:
      - mongodb_data:/data/db

volumes:
  webprotege_data:

  mongodb_data:
