version: '3'
services:
  ita-webprotege-web:
    image: dataservices.azurecr.io/ita-webprotege/web:latest
    ports:
      - "80:8080"
    volumes:
      - webprotege_data:/data/webprotege
    restart: always
  ita-webprotege-db:
    image: dataservices.azurecr.io/ita-webprotege/db:latest
    volumes:
      - mongodb_data:/data/db
    restart: always
volumes:
  webprotege_data:
  mongodb_data:
