version: '3'
services:
  ita-webprotege-web:
    image: itadevacr.azurecr.io/ita-webprotege/web:latest
    build:
      context: .
      dockerfile: Dockerfile
  ita-webprotege-db:
    image: mongo:3
