version: '3'
services:
  ita-webprotege-db:
    image: mongo:4.1-bionic
    volumes:
      - mongodb_data:/data/db
  ita-webprotege-web:
    image: protegeproject/webprotege
    volumes:
      - webprotege_data:/data/webprotege
volumes:
  webprotege_data:
  mongodb_data:
