apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: webprotege
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: evangelos.poneres@trade.gov
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
